//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by APRSISCE.rc
//
#define IDS_LABEL1                      16
#define IDS_LABEL2                      17
#define IDM_SATELLITE                   95
#define IDM_LOG                         96
#define IDM_CHAT                        97
#define IDM_MAIN                        98
#define IDM_MAIN_W32                    99
#define IDM_TRACKER                     100
#define IDR_BITMAP0                     101
#define IDR_BITMAP1                     102
#define IDD_SEND_MESSAGE                102
#define IDR_BITMAP2                     103
#define IDD_CONFIG                      103
#define IDR_BITMAP3                     104
#define IDD_GENIUS_BEACON               104
#define IDM_NOTIFY                      104
#define IDR_BITMAP4                     105
#define IDD_SEND_EMAIL                  105
#define IDB_BITMAP1                     105
#define IDR_BITMAP5                     106
#define IDB_BITMAP2                     106
#define IDD_SYMBOL                      106
#define IDD_STRING_PROMPT               107
#define IDD_NEW_RFPORT                  108
#define IDD_SEND_MESSAGE2               109
#define IDD_FIND_STATION                109
#define IDD_PORT_CONFIG                 110
#define IDI_MY_ICON                     110
#define IDD_BULLETIN                    111
#define IDD_OBJECT                      112
#define IDD_CQSRVR                      113
#define IDD_STATUS_REPORT               115
#define IDD_APRS_CONFIG                 116
#define IDD_APRSIS_CONFIG               116
#define IDD_SPIN_PROMPT                 117
#define IDD_TILE_SERVER                 118
#define IDD_NICKNAME                    119
#define IDD_DF                          121
#define IDD_DFS                         122
#define IDD_PHG                         123
#define IDD_COLOR                       124
#define IDD_PATHS                       125
#define IDD_VIEW                        126
#define IDD_OVERLAY                     127
#define IDD_COMPANION                   128
#define IDB_CANCEL                      1001
#define IDB_SYMBOL                      1002
#define IDB_SEND                        1003
#define IDL_TO_CALL                     1004
#define IDE_TEXT                        1005
#define IDS_RANGE                       1009
#define IDE_RANGE                       1010
#define IDE_FILTER                      1011
#define IDE_PASSWORD                    1012
#define IDE_COMMENT                     1013
#define IDE_RF_PATH                     1014
#define IDE_CALLSIGN                    1015
#define IDB_ACCEPT                      1016
#define IDB_GENIUS                      1017
#define IDB_MOVE                        1017
#define IDB_SHOW                        1018
#define IDE_MIN_TIME                    1019
#define IDB_NMEA                        1019
#define IDB_DF                          1019
#define IDE_MAX_TIME                    1020
#define IDB_TELEMETRY_PATH              1020
#define IDB_DFS                         1020
#define IDE_QUIET_TIME                  1021
#define IDE_BEARING_CHANGE              1022
#define IDE_FORECAST_ERROR              1023
#define IDE_MAX_DISTANCE                1024
#define IDS_MIN_TIME                    1025
#define IDL_EMAIL                       1026
#define IDS_MAX_TIME                    1027
#define IDS_QUIET_TIME                  1028
#define IDC_SYM_TEXT                    1028
#define IDS_BEARING_CHANGE              1029
#define IDC_SYM_SYMBOL                  1029
#define IDS_WIDTH_FIRST                 1029
#define IDS_FORECAST_ERROR              1030
#define IDS_WIDTH_MIDDLE                1030
#define IDS_MAX_DISTANCE                1031
#define IDS_WIDTH_FINAL                 1031
#define IDE_SYM_VALUE                   1032
#define IDS_WIDTH_PACKET                1032
#define IDS_WIDTH_ROUTES                1032
#define IDS_SYM_VALUE                   1033
#define IDS_OPACITY                     1033
#define IDS_WIDTH_TRACKS                1033
#define IDE_SYM_OVERLAY                 1034
#define IDS_OPACITY_ROUTES              1034
#define IDS_SYM_OVERLAY                 1035
#define IDS_OPACITY_TRACKS              1035
#define IDC_PRIMARY                     1040
#define IDC_ALTERNATE                   1041
#define IDE_IP_DNS                      1041
#define IDC_OVERLAY                     1042
#define IDE_PORT                        1042
#define IDC_PROMPT                      1042
#define IDL_TYPE                        1043
#define IDB_CREATE                      1044
#define IDL_COLOR_FIRST                 1044
#define IDB_FIND                        1045
#define IDL_COLOR_MIDDLE                1045
#define IDT_TEXT                        1046
#define IDL_COLOR_FINAL                 1046
#define IDB_MULTITRACK                  1047
#define IDL_COLOR_PACKET                1047
#define IDL_COLOR_ROUTES                1047
#define IDC_ENABLED                     1048
#define IDL_COLOR_TRACKS                1048
#define IDB_BEACON_PATH                 1049
#define IDC_KILL                        1049
#define IDC_GRIDSQUARE                  1049
#define IDC_STATUS                      1049
#define IDC_ENABLED2                    1049
#define IDC_OVERRIDE                    1049
#define IDB_DEVICE                      1050
#define IDC_TIMESTAMP                   1050
#define IDC_OVERRIDE_LABEL              1050
#define IDC_KILL2                       1050
#define IDL_RFBAUD                      1051
#define IDC_OVERRIDE_LABEL2             1051
#define IDC_OVERRIDE_COMMENT            1051
#define IDC_GRIDSQUARE2                 1051
#define IDC_DX                          1051
#define IDC_VIA_IS                      1052
#define IDC_OVERRIDE_LABEL3             1052
#define IDC_OVERRIDE_COLOR              1052
#define IDC_VIA_RF                      1053
#define IDC_MONITOR                     1053
#define IDC_OVERRIDE2                   1053
#define IDC_MULTI_NEW                   1053
#define IDL_LINE                        1054
#define IDC_VIA_CQSRVR                  1054
#define IDC_VIA_IS2                     1054
#define IDC_MULTI_ACTIVE                1054
#define IDL_GROUP                       1055
#define IDC_MULTI_ACTIVE2               1055
#define IDC_MULTI_ALWAYS                1055
#define IDE_INTERVAL                    1056
#define IDL_RANGE                       1056
#define IDS_INTERVAL                    1057
#define IDL_POWER                       1057
#define IDC_ACK                         1058
#define IDL_RANGE2                      1058
#define IDC_PRESENT                     1059
#define IDS_PORT                        1059
#define IDB_DELETE                      1060
#define IDC_TIME_ONLY                   1061
#define IDC_START_STOP                  1062
#define IDE_COMMENT_INTERVAL            1062
#define IDS_COMMENT_INTERVAL            1063
#define IDE_STATUS_TEXT                 1064
#define IDE_STATUS_INTERVAL             1065
#define IDS_STATUS_INTERVAL             1066
#define IDC_DHM                         1067
#define IDC_HMS                         1068
#define IDC_PERMANENT                   1069
#define IDC_ITEM                        1070
#define IDC_LOWER                       1071
#define IDC_SPIN_UNITS                  1072
#define IDC_UNITS                       1072
#define IDE_NAME                        1073
#define IDE_SERVER                      1074
#define IDE_URL                         1075
#define IDE_DAYS                        1076
#define IDS_DAYS                        1077
#define IDE_ZOOM1                       1078
#define IDS_ZOOM1                       1079
#define IDE_ZOOM2                       1080
#define IDS_ZOOM2                       1081
#define IDE_ZOOM3                       1082
#define IDS_ZOOM3                       1083
#define IDB_FLUSH                       1084
#define IDE_LABEL                       1085
#define IDB_FLUSH2                      1085
#define IDB_ABOUT                       1085
#define IDE_BEARING                     1086
#define IDS_BEARING                     1087
#define IDL_N                           1088
#define IDL_QUALITY                     1089
#define IDL_DIRECT                      1090
#define IDL_HEIGHT                      1093
#define IDL_GAIN                        1094
#define IDL_STRENGTH                    1096
#define IDE_RATE                        1097
#define IDS_RATE                        1098
#define IDC_BTPORT                      1099
#define IDB_PHG                         1100
#define IDB_SET_DESTINATION             1101
#define IDC_COMPRESSED                  1101
#define IDL_COLOR                       1102
#define IDC_COLORS                      1103
#define IDB_MORE                        1104
#define IDB_MORE2                       1105
#define IDB_LESS                        1106
#define IDC_COLORS_SHOWN                1107
#define IDC_CHECK1                      1108
#define IDC_VERIFY_CLOSE                1109
#define IDC_VERIFY_CLOSE2               1110
#define IDC_ABOUT_RESTART               1110
#define IDB_APPLY                       1111
#define IDB_UNDO                        1111
#define IDC_STATION_PACKET              1112
#define IDC_NETWORK_LINKS               1113
#define IDC_TYPE_DIRECT                 1114
#define IDC_TYPE_FIRST                  1115
#define IDC_TYPE_MIDDLE                 1116
#define IDC_TYPE_FINAL                  1117
#define IDE_WIDTH_DIRECT                1118
#define IDE_WIDTH_FIRST                 1119
#define IDE_WIDTH_MIDDLE                1120
#define IDC_LABEL_POINTS                1120
#define IDE_WIDTH_FINAL                 1121
#define IDS_WIDTH_DIRECT                1122
#define IDL_COLOR_DIRECT                1123
#define IDE_TIME_FLASH                  1124
#define IDC_FORCE_SYMBOL_POINTS         1124
#define IDS_TIME_FLASH                  1125
#define IDC_LABEL_ROUTES                1125
#define IDC_TIME_FLASH                  1126
#define IDC_SHOW_SYMBOL_POINTS          1126
#define IDE_TIME_SHORT                  1127
#define IDC_LABEL_TRACKS                1127
#define IDS_TIME_SHORT                  1128
#define IDC_SHOW_SYMBOL_ROUTES          1128
#define IDC_TIME_SHORT                  1129
#define IDC_SHOW_SYMBOL_TRACKS          1129
#define IDE_TIME_MEDIUM                 1130
#define IDS_TIME_MEDIUM                 1131
#define IDC_TIME_MEDIUM                 1132
#define IDE_TIME_LONG                   1133
#define IDS_WIDTH_DIRECT5               1134
#define IDS_TIME_LONG                   1134
#define IDC_TIME_LONG                   1135
#define IDC_SHOW_ALL                    1136
#define IDC_LABEL_NONE                  1136
#define IDE_WIDTH_PACKET                1137
#define IDC_LABEL_ID                    1137
#define IDC_TIME_ONE                    1138
#define IDC_TIME_ALL                    1139
#define IDE_OPACITY                     1140
#define IDC_LABEL_COMMENT               1140
#define IDB_DEFAULT                     1141
#define IDC_SHOW_ALL2                   1142
#define IDC_SHOW_RF_ONLY                1142
#define IDC_LABEL_STATUS                1142
#define IDB_UNDO2                       1143
#define IDB_MAX_LENGTH                  1143
#define IDC_LABEL_ALTITUDE              1143
#define IDB_MAX_LENGTH2                 1144
#define IDB_EXPERT                      1144
#define IDC_LABEL_TIME                  1144
#define IDB_CLEAR                       1145
#define IDC_SHOW_ALL3                   1145
#define IDC_SHOW_MY_PACKET              1145
#define IDC_LABEL_NODATE                1145
#define IDC_RF_ALL                      1146
#define IDC_SHOW_POINTS                 1146
#define IDC_RF_DIRECT                   1147
#define IDE_OPACITY_ROUTES              1147
#define IDC_RF_LOCAL                    1148
#define IDC_SHOW_ROUTES                 1148
#define IDC_RF_3RD                      1149
#define IDC_SHOW_TRACKS                 1149
#define IDC_XPORT_RF_ONLY               1150
#define IDC_FROM                        1150
#define IDE_OPACITY_TRACKS              1150
#define IDC_XPORT_RF_IS                 1151
#define IDT_UNITS                       1151
#define IDC_FROM2                       1151
#define IDC_XPORT_IS_ONLY               1152
#define IDC_VISIBLE                     1152
#define IDC_NETWORK_DIGI                1153
#define IDB_SYMBOL_POINTS               1153
#define IDC_NETWORK_IGATE               1154
#define IDC_BOX_POINTS                  1154
#define IDC_BUDDIES                     1155
#define IDE_WIDTH_ROUTES                1155
#define IDC_NICKNAMED                   1156
#define IDB_SYMBOL_ROUTES               1156
#define IDC_ATTR_ALTITUDE               1157
#define IDC_ATTR_ALTITUDES              1157
#define IDE_WIDTH_TRACKS                1157
#define IDC_ATTR_AMBIGUOUS              1158
#define IDB_SYMBOL_TRACKS               1158
#define IDC_ATTR_MSGS                   1159
#define IDC_BOX_ROUTES                  1159
#define IDC_ATTR_NWS                    1160
#define IDC_BOX_TRACKS                  1160
#define IDC_ATTR_OBJECTS                1161
#define IDC_ATTR_TELEMETRY              1162
#define IDC_ATTR_MSGS2                  1163
#define IDC_ATTR_FREQUENCIES            1163
#define IDC_ATTR_TRACKS                 1164
#define IDC_ATTR_PATHS                  1165
#define IDC_SYM_FLIGHT                  1166
#define IDC_SYM_MOBILE                  1167
#define IDC_SYM_RFID                    1168
#define IDC_SYM_WEATHER                 1169
#define IDC_SYM_CUSTOM                  1170
#define IDC_APRSISCE                    1171
#define IDC_APRSISCE2                   1172
#define IDC_APRSIS32                    1172
#define IDC_LAST_COUNT                  1173
#define IDC_ATTR_FREQUENCIES2           1174
#define IDC_ATTR_FREQSPEC               1174
#define IDC_SYM_MOBILE2                 1175
#define IDC_SYM_MARINE                  1175
#define IDC_APRSISCE3                   1176
#define IDC_APRSISDR                    1176
#define IDM_TLE_PASTE                   10001
#define IDM_TLE_FETCH                   10002
#define IDM_TLE_FILE                    10003
#define IDM_TLE_HIDE                    10004
#define ID_SATELLITE_DETAILS            11001
#define IDC_COMMPORT                    11001
#define IDC_BAUDRATE                    11002
#define IDR_NONE                        11003
#define IDR_EVEN                        11004
#define IDC_ODD                         11005
#define IDR_ODD                         11005
#define IDR_SEVEN                       11006
#define IDR_EIGHT                       11007
#define IDR_ONE                         11008
#define IDR_TWO                         11009
#define IDC_XMIT                        11010
#define IDC_NMEA                        11011
#define IDC_BEACON                      11012
#define IDC_TELEMETRY                   11013
#define IDC_RFTOIS                      11014
#define IDC_ISTORF                      11015
#define IDC_MENO3RD                     11016
#define IDC_NOGATEME                    11016
#define IDC_INHERIT                     11017
#define IDC_BULLETIN_OBJECT             11018
#define IDC_MESSAGE                     11019
#define IDC_BEACON2                     11020
#define IDC_DX2                         11020
#define ID_CONFIGURE_POSITS_PATHS       11026
#define ID_CONFIGURE_POSITS_FILTER      11027
#define ID_CONFIGURE_SCROLLER_CLICK_FREEZE 11028
#define ID_CONFIGURE_SCROLLER_SHOW_IGATE 11029
#define ID_CONFIGURE_SCROLLER_FILTER    11030
#define ID_CONFIGURE_SCROLLER_HIDE_NOPARSE 11031
#define ID_CONFIGURE_SCROLLER_NO_INTERNALS 11032
#define ID_CONFIGURE_SCROLLER_NOT_ME    11033
#define ID_CONFIGURE_SCROLLER_NOT_MINE  11034
#define ID_CONFIGURE_SCROLLER_RF_ONLY   11035
#define ID_CONFIGURE_SCROLLER_SHOW_ALL  11036
#define ID_CONFIGURE_DX_MIN_DIST        11037
#define ID_CONFIGURE_DX_MIN_TRIGGER     11038
#define ID_CONFIGURE_DX_MIN_INTERVAL    11039
#define ID_CONFIGURE_DX_WINDOW          11040
#define ID_CONFIGURE_DX_MAXEVER         11041
#define ID_CONFIGURE_DX_IGNORE_NONE     11042
#define ID_COMPANIONS_NEW               11045
#define ID_COMPANIONS_ENABLED           11046
#define ID_TACTICAL_ENABLE              11992
#define ID_OBJECTS_NEW                  11993
#define ID_OBJECT_GROUP_PATH            11994
#define ID_OBJECT_GROUP_INTERVAL        11995
#define ID_OBJECT_GROUP_VIA_RF          11996
#define ID_OBJECT_GROUP_VIA_IS          11997
#define ID_OBJECT_GROUP_ENABLE          11998
#define ID_OBJECT_GROUP_KILL            11999
#define ID_DYNAMIC_BASE                 12000
#define ID_DYNAMIC_MAX                  39000
#define ID_MAX_GROUP_OBJS               39994
#define ID_QRU_RETRY_MESSAGES           39995
#define ID_QRU_ENABLE                   39996
#define ID_QRU_INTERVAL                 39997
#define ID_QRU_MAX_OBJS                 39998
#define ID_QRU_RANGE                    39999
#define ID_EXIT                         40001
#define ID_TRANSMIT                     40002
#define ID_SEND_MESSAGE                 40003
#define ID_ABOUT                        40004
#define ID_SEND_EMAIL                   40010
#define ID_READ_MESSAGES                40011
#define ID_MESSAGES_EAVESDROP           40012
#define ID_RF_MESSAGES                  40013
#define ID_MY_MESSAGES                  40014
#define ID_MESSAGES_HIDE_QUERIES        40015
#define ID_MESSAGES_NOTIFY_ON_QUERY     40016
#define ID_MESSAGES_NOTIFY_ON_NEW       40017
#define ID_MESSAGES_MULTITRACK_ITEM     40018
#define ID_READ_MESSAGE                 40019
#define ID_PENDING_MESSAGES             40020
#define ID_MESSAGES_HIDE_NWS            40021
#define ID_MENU_REPLY                   40024
#define ID_MENU_DISMISS                 40025
#define ID_VIEW_PREFERRED_RESTORE       40026
#define ID_VIEW_PREFERRED_SAVE          40027
#define ID_VIEW_PREFERRED_MULTITRACK_SIZE 40028
#define ID_VIEW_PREFERRED_MULTITRACK_ZOOM 40029
#define ID_VIEW_PREFERRED_MULTITRACK_PERCENT 40030
#define ID_VIEW_PREFERRED_MULTITRACK_NONE 40031
#define ID_CONFIG_MAP_PREFETCH          40032
#define ID_CONFIG_MAP_PURGER            40033
#define ID_VIEW_PORTRAIT                40034
#define ID_VIEW_LANDSCAPE               40035
#define ID_VIEW_AUTOMATIC               40036
#define ID_ALIASES_KNOWN_NEW            40040
#define ID_ALIASES_ACCUMULATE           40041
#define ID_ALIASES_POSSIBLE_CLEAR       40042
#define ID_ALIASES_0_CLEAR              40043
#define ID_SCREEN_BRIGHT                40082
#define ID_SCREEN_DIM                   40083
#define ID_ZOOM_IN                      40084
#define ID_ZOOM_OUT                     40085
#define ID_FADE_IN                      40086
#define ID_FADE_OUT                     40087
#define ID_SCREEN_AUTOZOOM_VIEW_CTR     40089
#define ID_SCREEN_AUTOZOOM_VIEW         40090
#define ID_SCREEN_AUTOZOOM_VIEW_IN      40091
#define ID_SCREEN_AUTOZOOM_VIEW_OUT     40092
#define ID_SCREEN_TRACK_FIND            40093
#define ID_VIEW_NONE                    40098
#define ID_VIEW_CHOOSER                 40099
#define ID_VIEW_ALL                     40100
#define ID_VIEW_BUDDIES                 40101
#define ID_VIEW_DUPLICATES              40102
#define ID_VIEW_INVALIDS                40103
#define ID_VIEW_MESSAGEABLE             40104
#define ID_VIEW_NWS                     40105
#define ID_VIEW_OBJECTS                 40106
#define ID_VIEW_SHRIEKS                 40107
#define ID_VIEW_TELEMETRY               40108
#define ID_VIEW_TRACKS                  40109
#define ID_VIEW_ECHOLINKS               40110
#define ID_VIEW_GEOCACHES               40111
#define ID_VIEW_RF_ALL                  40112
#define ID_VIEW_RF_DIRECT               40113
#define ID_VIEW_RF_LOCAL                40114
#define ID_VIEW_RF_THIRD                40115
#define ID_VIEW_RF_ONLY                 40116
#define ID_VIEW_RF_DIGI                 40117
#define ID_VIEW_RF_INTERNET             40118
#define ID_VIEW_RF_IGATE                40119
#define ID_VIEW_INTERNET_ONLY           40120
#define ID_VIEW_RFID                    40121
#define ID_VIEW_MARINE                  40122
#define ID_VIEW_MOBILE                  40123
#define ID_VIEW_WEATHER                 40124
#define ID_VIEW_FLIGHT                  40125
#define ID_VIEW_CUSTOM                  40126
#define ID_VIEW_AMBIGUOUS               40127
#define ID_VIEW_NICKNAMES               40128
#define ID_VIEW_ANSRVR_MEMBERS          40129
#define ID_VIEW_PLATFORMS               40130
#define ID_VIEW_SYMBOLS                 40132
#define ID_VIEW_ALTITUDES               40133
#define ID_VIEW_PATHS                   40134
#define ID_VIEW_FREQUENCIES             40135
#define ID_VIEW_FREQSPEC                40136
#define ID_VIEW_MICE                    40137
#define ID_CLEAR_WINDOW_POSITIONS       40201
#define ID_CLEAR_PATHS                  40202
#define ID_RESET_MAX_WIDTH              40203
#define ID_CLEAR_TRACK                  40204
#define ID_CLEAR_TACTICAL               40205
#define ID_CLEAR_STATIONS               40206
#define ID_CLEAR_TELEMETRY              40207
#define ID_CLEAR_BULLETINS              40208
#define ID_CLEAR_WEATHER                40209
#define ID_CLEAR_BEACON_COMMENTS        40210
#define ID_CLEAR_STATUS_TEXTS           40211
#define ID_CLEAR_SYMBOLS                40212
#define ID_CLEAR_ALTNETS                40213
#define ID_CLEAR_AUTO_REPLIES           40214
#define ID_CLEAR_MICE_IGNORES           40215
#define ID_CLEAR_TACTICAL_ACCEPTS       40216
#define ID_CLEAR_TACTICAL_NEVERS        40217
#define ID_MESSAGES_PURGE_EAVESDROP     40230
#define ID_MESSAGES_PURGE_MY            40231
#define ID_MESSAGES_PURGE_NWS           40232
#define ID_MESSAGES_PURGE_GROUP         40233
#define ID_MESSAGES_PURGE_SPECIAL       40234
#define ID_AUTO_REPLY_DELAY_ALWAYS      40300
#define ID_AUTO_REPLY_DELAY_1_MIN       40301
#define ID_AUTO_REPLY_DELAY_5_MIN       40302
#define ID_AUTO_REPLY_DELAY_10_MIN      40303
#define ID_AUTO_REPLY_DELAY_30_MIN      40304
#define ID_AUTO_REPLY_DELAY_LONGER      40305
#define ID_AUTO_REPLY_DELAY_FOREVER     40306
#define ID_AUTO_REPLY_INTERVAL_1_MIN    40310
#define ID_AUTO_REPLY_INTERVAL_10_MIN   40311
#define ID_AUTO_REPLY_INTERVAL_30_MIN   40312
#define ID_AUTO_REPLY_INTERVAL_1_HOUR   40313
#define ID_AUTO_REPLY_INTERVAL_1_DAY    40314
#define ID_AUTO_REPLY_INTERVAL_1_YEAR   40315
#define ID_AUTO_REPLY_INTERVAL_LONGER   40316
#define ID_AUTO_REPLY_INTERVAL_FOREVER  40317
#define ID_SCREEN_LABEL_NICKNAMES       40963
#define ID_SCREEN_LABEL_NICKNAME_DELETE 40964
#define ID_CONFIGURE_PATHS              40965
#define ID_SCREEN_PATHS_MYSTATION       40966
#define ID_SCREEN_PATHS_STATION         40967
#define ID_SCREEN_PATHS_NETWORK         40968
#define ID_SCREEN_PATHS_RFONLY          40969
#define ID_SCREEN_FOOTPRINT             40970
#define ID_SCREEN_FOOTPRINT_MIN         40971
#define ID_SCREEN_FOOTPRINT_MAX         40972
#define ID_SCREEN_TRACKS_FOLLOW         40973
#define ID_SCREEN_TRACKS_FOLLOW_COLOR   40974
#define ID_SCREEN_TRACKS_FOLLOW_WIDTH   40975
#define ID_SCREEN_TRACKS_OTHER          40976
#define ID_SCREEN_TRACKS_OTHER_COLOR    40977
#define ID_SCREEN_TRACKS_OTHER_WIDTH    40978
#define ID_SCREEN_TRACKS_OTHER_ADD_COLOR 40979
#define ID_TRACK_COLOR_SELECT           40980
#define ID_SCREEN_SYMBOL_SIZE_ADJUST    40981
#define ID_SCREEN_SPEED_FONT            40982
#define ID_SCREEN_LABEL_OVERLAP         40983
#define ID_SCREEN_LABEL_CELLULAR        40985
#define ID_SCREEN_LABEL_NWS             40986
#define ID_SCREEN_LABEL_WEATHER         40987
#define ID_SCREEN_SPEED_BEACONED        40988
#define ID_SCREEN_SPEED_CALCULATED      40989
#define ID_SCREEN_SPEED_AVERAGED        40990
#define ID_SCREEN_SPEED_ALL             40991
#define ID_SCREEN_TRACK_ME              40992
#define ID_SCREEN_CENTER_TRACKED        40993
#define ID_SCREEN_TRACK_LOCKED          40994
#define ID_SCREEN_DEAD_RECKON           40995
#define ID_SCREEN_FILTER_CIRCLE         40996
#define ID_SCREEN_TRACKS                40997
#define ID_SCREEN_LABEL_ALTITUDE        40998
#define ID_SCREEN_SATELLITES            40999
#define ID_SCREEN_CALLSIGN              41000
#define ID_SCREEN_CALLSIGN_NOT_ME       41001
#define ID_SCREEN_CALLSIGN_NOT_MINE     41002
#define ID_SCREEN_LATLON                41003
#define ID_SCREEN_GRIDSQUARE            41004
#define ID_SCREEN_DATETIME_NONE         41005
#define ID_SCREEN_DATETIME_LOCAL        41006
#define ID_SCREEN_DATETIME_GMT          41007
#define ID_SCREEN_DATETIME_GPS_ONLY     41008
#define ID_SCREEN_DATETIME_DATE_ONLY    41009
#define ID_SCREEN_DATETIME_TIME_ONLY    41010
#define ID_SCREEN_DATETIME_0            41011
#define ID_SCREEN_DATETIME_1            41012
#define ID_SCREEN_DATETIME_2            41013
#define ID_SCREEN_DATETIME_3            41014
#define ID_SCREEN_DATETIME_4            41015
#define ID_SCREEN_DATETIME_5            41016
#define ID_SCREEN_DATETIME_6            41017
#define ID_SCREEN_DATETIME_7            41018
#define ID_SCREEN_DATETIME_8            41019
#define ID_SCREEN_DATETIME_9            41020
#define ID_SCREEN_DATETIME_DEFAULT      41021
#define ID_SCREEN_DATETIME_PERFORMANCE  41022
#define ID_SCREEN_ALTITUDE              41023
#define ID_SCREEN_BATTERY               41024
#define ID_SCREEN_CIRCLE                41025
#define ID_SCREEN_RED_DOT               41026
#define ID_SCREEN_CROSSHAIRS_NEVER      41027
#define ID_SCREEN_CROSSHAIRS_ALWAYS     41028
#define ID_SCREEN_CROSSHAIRS_TIMED      41029
#define ID_SCREEN_LABEL_AMBIGUITY       41030
#define ID_SCREEN_GEOCACHE_ID           41031
#define ID_SCREEN_GEOCACHE_TYPE         41032
#define ID_SCREEN_GEOCACHE_CONT         41033
#define ID_SCREEN_GEOCACHE_DT           41034
#define ID_SCREEN_LABEL_MAX             41035
#define ID_SCREEN_GEOCACHE_LABEL_MAX    41036
#define ID_SCREEN_WINDBARBS_ENABLED     41037
#define ID_SCREEN_WINDBARBS_COLOR       41038
#define ID_SCREEN_WINDBARBS_WIDTH       41039
#define ID_SCREEN_WINDBARBS_ROTATE      41040
#define ID_FREQ_TOGGLE                  42000
#define ID_GPS_TOGGLE                   42001
#define ID_APRS_TOGGLE                  42002
#define ID_SOUND_TOGGLE                 42003
#define ID_BEACON_TOGGLE                42004
#define ID_INTERNET_TOGGLE              42005
#define ID_TELEMETRY_TOGGLE             42006
#define ID_OSM_TOGGLE                   42008
#define ID_CSV_TOGGLE                   42009
#define ID_AUTOSAVE_GPX                 42010
#define ID_OBJECTS_BEARING              42051
#define ID_OBJECTS_MOVE                 42052
#define ID_OBJECTS_NEW_WEATHER          42053
#define ID_OBJECTS_NEW_DF               42054
#define ID_OBJECTS_NEW_DF_CENTER        42055
#define ID_OBJECTS_SHOW                 42056
#define ID_OBJECTS_KILL                 42057
#define ID_OBJECTS_ENABLE               42058
#define ID_OBJECTS_ENABLE_IS            42059
#define ID_OBJECTS_ENABLE_RF            42060
#define ID_OBJECTS_OFFSET               42061
#define ID_OBJECTS_WIDTH                42062
#define ID_OBJECTS_NEW_JT65             42063
#define IDM_OBJ_AREA_SHAPE              42110
#define ID_OBJ_AREA_SHAPE_LOWEST        42110
#define ID_OBJ_AREA_SHAPE_OPEN_CIRCLE   42110
#define ID_OBJ_AREA_SHAPE_LINE_DOWN_RIGHT 42111
#define ID_OBJ_AREA_SHAPE_OPEN_ELLIPSE  42112
#define ID_OBJ_AREA_SHAPE_OPEN_TRIANGLE 42113
#define ID_OBJ_AREA_SHAPE_OPEN_BOX      42114
#define ID_OBJ_AREA_SHAPE_FILLED_CIRCLE 42115
#define ID_OBJ_AREA_SHAPE_LINE_DOWN_LEFT 42116
#define ID_OBJ_AREA_SHAPE_FILLED_ELLIPSE 42117
#define ID_OBJ_AREA_SHAPE_FILLED_TRIANGLE 42118
#define ID_OBJ_AREA_SHAPE_FILLED_BOX    42119
#define ID_OBJ_AREA_SHAPE_HIGHEST       42119
#define IDM_OBJ_AREA_COLOR              42120
#define ID_OBJ_AREA_COLOR_LOWEST        42120
#define ID_OBJ_AREA_COLOR_HIGH_BLACK    42120
#define ID_OBJ_AREA_COLOR_HIGH_BLUE     42121
#define ID_OBJ_AREA_COLOR_HIGH_GREEN    42122
#define ID_OBJ_AREA_COLOR_HIGH_CYAN     42123
#define ID_OBJ_AREA_COLOR_HIGH_RED      42124
#define ID_OBJ_AREA_COLOR_HIGH_MAGENTA  42125
#define ID_OBJ_AREA_COLOR_HIGH_YELLOW   42126
#define ID_OBJ_AREA_COLOR_HIGH_GRAY     42127
#define ID_OBJ_AREA_COLOR_MEDIUM_GRAY   42128
#define ID_OBJ_AREA_COLOR_LOW_BLUE      42129
#define ID_OBJ_AREA_COLOR_LOW_GREEN     42130
#define ID_OBJ_AREA_COLOR_LOW_CYAN      42131
#define ID_OBJ_AREA_COLOR_LOW_RED       42132
#define ID_OBJ_AREA_COLOR_LOW_MAGENTA   42133
#define ID_OBJ_AREA_COLOR_LOW_YELLOW    42134
#define ID_OBJ_AREA_COLOR_LIGHT_GRAY    42135
#define ID_OBJ_AREA_COLOR_HIGHEST       42135
#define IDM_DF_QUALITY                  42140
#define ID_DF_QUALITY_BASE              42140
#define ID_DF_QUALITY_240               42141
#define ID_DF_QUALITY_120               42142
#define ID_DF_QUALITY_64                42143
#define ID_DF_QUALITY_32                42144
#define ID_DF_QUALITY_16                42145
#define ID_DF_QUALITY_8                 42146
#define ID_DF_QUALITY_4                 42147
#define ID_DF_QUALITY_2                 42148
#define ID_DF_QUALITY_1                 42149
#define ID_CONFIGURE_GENERAL            45001
#define ID_CONFIGURE_GENIUS             45002
#define ID_CONFIGURE_STATUS_TEXT        45003
#define ID_VIEW_METRIC_TEMPERATURE      45007
#define ID_VIEW_METRIC_DISTANCE         45008
#define ID_VIEW_METRIC_ALTITUDE         45009
#define ID_VIEW_METRIC_PRESSURE         45010
#define ID_VIEW_METRIC_RAINFALL         45011
#define ID_VIEW_METRIC_WINDSPEED        45012
#define ID_SCREEN_RANGE_FULL            45020
#define ID_SCREEN_RANGE_HALF            45021
#define ID_SCREEN_RANGE_OPACITY         45022
#define ID_SCREEN_DF_ENABLED            45023
#define ID_SCREEN_DF_OPACITY            45024
#define ID_CONFIGURE_BEACON_AFTER_TRANSMIT 45109
#define ID_CONFIGURE_BEACON_TIMESTAMP   45110
#define ID_CONFIGURE_BEACON_HHMMSS      45111
#define ID_CONFIGURE_BEACON_COMPRESSED  45112
#define ID_CONFIGURE_BEACON_CSESPD      45113
#define ID_CONFIGURE_BEACON_ALTITUDE    45114
#define ID_CONFIGURE_BEACON_PRESSURE    45115
#define ID_CONFIGURE_BEACON_DAO_0       45116
#define ID_CONFIGURE_BEACON_DAO_1       45117
#define ID_CONFIGURE_BEACON_DAO_2       45118
#define ID_CONFIGURE_BEACON_PATH        45119
#define ID_CONFIGURE_BEACON_CELLULAR    45120
#define ID_CONFIGURE_BEACON_AMBIG_1     45121
#define ID_CONFIGURE_BEACON_AMBIG_2     45122
#define ID_CONFIGURE_BEACON_AMBIG_3     45123
#define ID_CONFIGURE_BEACON_AMBIG_4     45124
#define ID_CONFIGURE_BEACON_MICE_NONE   45125
#define ID_CONFIGURE_WHOIS_BRIEF        45130
#define ID_CONFIGURE_WHOIS_FULL         45131
#define ID_CONFIGURE_MICE_NOTIF_SUPPRESSED 45132
#define ID_CONFIGURE_MICE_NOTIF_NO_EMERGENCY 45133
#define ID_CONFIGURE_NWS_MULTITRACK_ME  45150
#define ID_CONFIGURE_NWS_MULTITRACK_RANGE 45151
#define ID_CONFIGURE_NWS_MULTITRACK_MOVING 45152
#define ID_CONFIGURE_NWS_MULTITRACK_CLOSE 45153
#define ID_CONFIGURE_NWS_MULTITRACK_LINES 45154
#define ID_CONFIGURE_NWS_MULTITRACK_SPECIFIC 45155
#define ID_CONFIGURE_NWS_MULTITRACK_NEW 45156
#define ID_CONFIGURE_NWS_MULTITRACK     45157
#define IDM_CHAT_W32                    49999
#define IDM_LOG_W32                     50000
#define ID_LOG_HIDE                     50001
#define ID_LOG_CLEAR                    50002
#define ID_LOG_COPY                     50003
#define ID_LOG_ENABLE                   50004
#define ID_LOG_GENERAL                  50097
#define ID_LOG_FILE                     50098
#define ID_LOG_NONE                     50099
#define ID_LOG_ALL                      50100
#define ID_LOG_STARTUP                  50200
#define ID_RFPORTS_NO_XMIT              50398
#define ID_RFPORTS_LOG_ALL              50399
#define ID_RFPORTS_ENABLE               50400
#define ID_CONFIGURE_NEW_RFPORT         50498
#define ID_CONFIGURE_APRSIS             50499
#define ID_CONFIGURE_NMEA               50500
#define ID_BULLETINS_VIEW               50598
#define ID_BULLETINS_NOTIFY_NEW         50599
#define ID_BULLETINS_NEW                50600
#define ID_CQSRVR_ACTIVE_GROUPS         50700
#define ID_CQSRVR_DESCRIBE_GROUPS       50701
#define ID_CQSRVR_MEMBER_GROUPS         50702
#define ID_CQSRVR_JOIN_GROUP            50703
#define ID_CHAT_NEW                     50800
#define ID_VIEW_PLATFORMS_NONE          50900
#define ID_CONFIGURE_BEACON_COMMENT_NEW 51000
#define ID_CONFIGURE_BEACON_COMMENT_NONE 51001
#define ID_CONFIGURE_STATUS_TEXT_ENABLED 51100
#define ID_CONFIGURE_STATUS_TEXT_CELLULAR 51101
#define ID_CONFIGURE_STATUS_TEXT_GRIDSQ 51102
#define ID_CONFIGURE_STATUS_TEXT_TIME   51103
#define ID_CONFIGURE_STATUS_TEXT_NEW    51104
#define ID_CONFIGURE_STATUS_TEXT_NONE   51105
#define ID_CONFIGURE_STATUS_TEXT_DX     51106
#define ID_CONFIGURE_SYMBOL_NEW         51200
#define ID_CONFIGURE_AUTO_REPLY_NEW     51300
#define ID_CONFIGURE_AUTO_REPLY_NONE    51399
#define ID_CONFIGURE_NWS_NEW_OFFICE     51400
#define ID_CONFIGURE_NWS_SHOW_OFFICES_ALL 51495
#define ID_CONFIGURE_NWS_SHOW_OFFICES   51496
#define ID_CONFIGURE_NWS_MESSAGES       51497
#define ID_CONFIGURE_NWS_MESSAGES_NO_ALL 51498
#define ID_CONFIGURE_NWS_NOTIFY         51499
#define ID_CONFIGURE_NWS_ENTRY_SERVER   51500
#define ID_CONFIGURE_NWS_PRODUCTS       51600
#define ID_CONFIGURE_MULTILINE_STYLE    51700
#define ID_CONFIGURE_NWS_NEW_SHAPEFILE  51800
#define ID_CONFIGURE_NWS_SHAPE_TEST     51896
#define ID_CONFIGURE_NWS_SHAPE_QUALITY  51897
#define ID_CONFIGURE_NWS_SHAPE_OPACITY  51898
#define ID_CONFIGURE_NWS_SHAPES_ENABLED 51899
#define ID_CONFIGURE_NEW_TILE_SERVER    51900
#define ID_SELECT_TILE_SERVER           52000
#define ID_CONFIGURE_NICKNAME_NEW       52100
#define ID_CONFIGURE_NICKNAME_DELETE    52101
#define ID_CONFIGURE_GPX_NEW            52300
#define ID_CONFIGURE_OVERLAY_NEW        52399
#define ID_CONFIGURE_ALTNET_NEW         53000
#define ID_CONFIGURE_ALTNET_NONE        54999
#define ID_VIEW_SHRIEKS_NONE            55000
#define ID_VIEW_MICE_NONE               55100
#define ID_VIEW_SYMBOLS_NONE            56000
#define ID_MULTITRACK_MENU              60000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         40034
#define _APS_NEXT_CONTROL_VALUE         1161
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
